### ISSUE TITLE
Error while creating Ingress

### ISSUE THREAD

**Issue by jnbptstm** [patoarvizu/terraform-kubernetes-notary#3]
When adding configuration for Ingress (at least, _ingress_hosts_ input variable), this error occurs :
```
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/notary/ingress.tf line 15, in resource "kubernetes_ingress" "ingress":
│   15:         host = rule.host
│ 
│ This object does not have an attribute named "host".
```

Replacing `host = rule.host` by `host = rule.value.host` in _ingress.tf_ should fix it.
# PR : Fix dynamic value for host in ingress #4

**Comment by patoarvizu** [comment]
Done in #4
